#
# Module manifest for 'SimpleSupervisorDeploymentAtScale'
# Generated by: Broadcom
# Generated on: 2025-01-22
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SimpleSupervisorDeploymentAtScale.psm1'

# Version number of this module.
ModuleVersion = '1.0.0.3'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

# Author of this module
Author = 'Broadcom'

# Company or vendor of this module
CompanyName = 'Broadcom'

# Copyright statement for this module
Copyright = 'Copyright (c) 2025 Broadcom. All Rights Reserved.'

# Description of the functionality provided by this module
Description = @'
Automates the simple end-to-end deployment of a vSphere Supervisor in VMware Cloud Foundation 9.x.
The module handles all aspects of the deployment including:
- vCenter and ESX host connection
- ESX Cluster creation and host add
- Datastore creation and storage policy configuration
- Virtual Distributed Switch (VDS) setup and port group configuration
- vSphere Supervisor Deployment
- ArgoCD installation and configuration for GitOps workflows
'@

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This requirement is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This requirement is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ ModuleName = 'VCF.PowerCLI'; ModuleVersion = '9.0' }
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module. For best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Copy-SimpleSupervisorTemplates',
    'Show-InfrastructureJsonConfigurationHelp',
    'Show-SupervisorJsonConfigurationHelp',
    'Start-SimpleSupervisorDeploymentAtScale'
)

# Cmdlets to export from this module. For best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module. For best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'Templates/infrastructure.json',
    'Templates/supervisor.json',
    'Templates/argocd-deployment.yml',
    'Templates/1.0.1-24896502.yml',
    'Templates/infrastructure-config-help.json',
    'Templates/supervisor-config-help.json'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('VMware', 'VCF', 'vSphere', 'Supervisor', 'Kubernetes', 'ArgoCD', 'Deployment', 'Automation', 'VKS')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/vmware/powershell-module-for-simple-supervisor-deployment-at-scale/blob/main/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/vmware/powershell-module-for-simple-supervisor-deployment-at-scale'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/vmware/powershell-module-for-simple-supervisor-deployment-at-scale/main/.github/icon-85px.svg'

        # ReleaseNotes of this module
        #ReleaseNotes = @'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# URI of a help page for this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

